In [1]:
import tensorflow as tf


In [10]:
with tf.compat.v1.Session() as sess:
    const_tf = tf.constant([1,2])
    session = sess.run(const_tf)
    print(session)

[1 2]


In [22]:
with tf.compat.v1.Session() as sess:
    x = tf.compat.v1.placeholder(tf.string)
    y = tf.compat.v1.placeholder(tf.float32)
    z = tf.compat.v1.placeholder(tf.int32)
    plc = sess.run(z, feed_dict={x:"hello", y:123, z:25})
    print(plc)


25


### Quiz

In [33]:
#tensorflow 1
import tensorflow.compat.v1 as tf

def run():
    output = None
    

    with tf.Session() as sess:
        # TODO: Feed the x tensor 123
        x = tf.placeholder(tf.int32)
        output = sess.run(x, feed_dict={x:123})
    return output

print(run())




array(123)

In [43]:
#tensorflow 2
import tensorflow as tf

x = tf.Variable(123, name="y", dtype=tf.float32)
tf.print(x)
x

123


<tf.Variable 'y:0' shape=() dtype=float32, numpy=123.0>

In [54]:
import tensorflow as tf

add = tf.add(5,4)
tf.print(add)
sub = tf.subtract(54,6)
tf.print(sub)
mul = tf.multiply(4,5)
tf.print(mul)

x = tf.constant(1.0)
y = tf.constant(2)
output = tf.add(tf.cast(x, tf.int32), y)
tf.print(output)

x = tf.Variable(3)
y = tf.Variable(4)
output = tf.subtract(y, x)
tf.print(output)

9
48
20
3
1


### Quiz

In [56]:
# x = 10
# y = 2
# z = x/y - 1

import tensorflow as tf

x = tf.Variable(10)
y = tf.Variable(2)
z = tf.subtract(tf.cast(tf.divide(x,y), tf.int32), tf.cast(1, tf.int32))
tf.print(z)

4


In [10]:
#softmax
import numpy as np

def softmax(logits):
    return [np.exp(logits[i])/sum(np.exp(logits)) for i in range(len(logits))]
    # return np.exp(logits) / np.sum(np.exp(logits), axis=0)


logits = [3.0, 1.0, 0.2]
print(softmax(logits))
logits = [1.0, 2.0, 3.0]
# softmax will return a one-dimensional array with 3 elements
print(softmax(logits))
logits = np.array([
    [1, 2, 3, 6],
    [2, 4, 5, 6],
    [3, 8, 7, 6]])
# softmax will return a two-dimensional array with the same shape
for i in softmax(logits):
    print(i)

[0.8360188027814407, 0.11314284146556011, 0.05083835575299916]
[0.09003057317038046, 0.24472847105479767, 0.6652409557748219]
[0.09003057 0.00242826 0.01587624 0.33333333]
[0.24472847 0.01794253 0.11731043 0.33333333]
[0.66524096 0.97962921 0.86681333 0.33333333]


In [22]:
#softmax tensorflow
import tensorflow as tf

logits = [1.2, .9, .4]
prob = tf.nn.softmax(logits)
tf.print(prob)

[0.456590325 0.338250399 0.205159247]


In [24]:
logits = [12., 10., 7.]
prob = tf.nn.softmax(logits)
tf.print(prob)

[0.875600576 0.118499652 0.00589975]


In [25]:
logits = [0.12, .09, .04]
prob = tf.nn.softmax(logits)
tf.print(prob)

[0.345594823 0.335380942 0.319024235]


In [2]:
a = 1000000000
for i in range(1000000):
    a=a + 1e-6
print(a-1000000000)

0.95367431640625


In [1]:
from tensorflow.keras.datasets import mnist
(X_train, Y_train), (X_test, Y_test) = mnist.load_data()

10305536/11490434 [=========================>....] - ETA: 23s

ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine